rem LICENSE INFORMATION

rem this script is voluntarily released into the public domain via the Creative Commons Zero License (https://creativecommons.org/share-your-work/public-domain/cc0/):

rem To the extent possible under law, SparkliTwizzl has waived all copyright and related or neighboring rights to this file. This work is published from: United States.



rem newline hack to allow single-echo line breaks
rem note: must be used as !nl!, not %nl%
setlocal EnableDelayedExpansion
(set nl=^
%=intentionallyEmpty=%
)

cd %localhost%
@echo off



:generateLicenseFile
echo %~n0%~x0 is voluntarily released into the public domain via the Creative Commons Zero License (https://creativecommons.org/share-your-work/public-domain/cc0/):!nl!!nl!To the extent possible under law, SparkliTwizzl has waived all copyright and related or neighboring rights to %~n0%~x0. This work is published from: United States.>LICENSE

:init
set version=0.1

set inputFile=testInput.akf
set outputFile=testOutput.ahk

echo ;generated by %~n0%~x0 v%version% on %date%!nl!>%outputFile%

:readInputData
set inputDataLineCount=0
for /f "tokens=*" %%x in (%inputFile%) do (
    set inputData[!inputDataLineCount!]=%%x
    set /a inputDataLineCount+=1
)

call :parseInputData %inputDataLineCount%-1

:parseInputData <endAt>
set /a endAt=%1%
echo parseInputData ; inputDataLineCount=%inputDataLineCount% ; endAt=%endAt%
for /l %%i in (0 1 %endAt%) do (
    if !inputData[%%i]!=={ (
        echo parseInputData ; i=%%i ; token=!inputData[%%i]!
        pause
        call :parseEntry %%i+1 & set /a %%i=!errorlevel!
        echo parseEntry return value=%%i
    )
)
exit /b

:parseEntry <startIndex>
set /a startIndex=%1%

echo parseEntry ; startIndex=%startIndex%
for /l %%j in (%startIndex% 1 %endAt%) do (
    echo parseEntry ; j=%%j ; token=!inputData[%%j]!
    pause
    if !inputData[%%j]!==} (
        echo parseEntry ; j=%%j
        echo parseEntry ; exit ; returnIndex=%%j!nl!!nl!
        pause
        exit /b %%j
    )
)


pause
