rem LICENSE INFORMATION

rem this script is voluntarily released into the public domain via the Creative Commons Zero License (https://creativecommons.org/share-your-work/public-domain/cc0/):

rem To the extent possible under law, SparkliTwizzl has waived all copyright and related or neighboring rights to this file. This work is published from: United States.



:main <inputFilepath> <outputFilepath> <shouldGenerateLicenseFile>
set inputFile=$~1
set outputFile=$~2
set shouldGenerateLicenseFile=$~3

call :init
call :generateLicenseFile
call :readInputData
call :parseInputData 0
call :writeOutput
exit /b



:init
cd %localhost%
@echo off

rem newline hack to allow single-echo line breaks
rem note: must be used as !nl!, not %nl%, since it relies on delayed expansion
setlocal EnableDelayedExpansion
(set nl=^
%=intentionallyEmpty=%
)

set version=0.1
set inputFile=testInput.akf
set outputFile=testOutput.ahk
echo ;generated by %~n0%~x0 v%version% on %date%!nl!>%outputFile%
exit /b



:generateLicenseFile
echo %~n0%~x0 is voluntarily released into the public domain via the Creative Commons Zero License (https://creativecommons.org/share-your-work/public-domain/cc0/):!nl!!nl!To the extent possible under law, SparkliTwizzl has waived all copyright and related or neighboring rights to %~n0%~x0. This work is published from: United States.>LICENSE
exit /b



:readInputData
set inputDataLineCount=0
for /f "tokens=*" %%x in (%inputFile%) do (
    set inputData[!inputDataLineCount!]=%%x
    set /a inputDataLineCount+=1
)
exit /b



:parseInputData <lineIndex>
set /a lineIndex=%~1
if %lineIndex%==%inputDataLineCount% (
    exit /b
)

if !inputData[%%i]!=={ (
    echo parseInputData ; i=%%i ; token=!inputData[%%i]!
    pause
    call :parseEntry %%i+1 & set /a %%i=!errorlevel!
    echo parseEntry return value=%%i
)



:parseEntry <lineIndex>
set /a lineIndex=%1%

echo parseEntry ; lineIndex=%lineIndex%
for /l %%j in (%lineIndex% 1 %endIndex%) do (
    echo parseEntry ; j=%%j ; token=!inputData[%%j]!
    pause
    if !inputData[%%j]!==} (
        echo parseEntry ; j=%%j
        echo parseEntry ; exit ; returnIndex=%%j!nl!!nl!
        pause
        exit /b %%j
    )
)
exit /b
