setlocal EnableDelayedExpansion
(set nl=^
%=intentionallyEmpty=%
)
REM note: must be used as !nl!, not %nl%

cd %localhost%
@echo off

set version=0.1

set inputPath="testInput.akf"
set outputPath="testOutput.ahk"

echo ;generated by %~n0 v%version% on %date%!nl!>%outputPath%

set readMember=true
:ReadMembers
