rem LICENSE INFORMATION

rem this script is voluntarily released into the public domain via the Creative Commons Zero License (https://creativecommons.org/share-your-work/public-domain/cc0/):

rem To the extent possible under law, SparkliTwizzl has waived all copyright and related or neighboring rights to this file. This work is published from: United States.



rem newline hack to allow single-echo line breaks
rem note: must be used as !nl!, not %nl%
setlocal EnableDelayedExpansion
(set nl=^
%=intentionallyEmpty=%
)

cd %localhost%
@echo off



set version=0.1

set inputFile="testInput.akf"
set outputFile="testOutput.ahk"

echo ;generated by %~n0 v%version% on %date%!nl!>%outputFile%



set readMember=true
:ReadMembers
