rem LICENSE INFORMATION

rem this script is voluntarily released into the public domain via the Creative Commons Zero License (https://creativecommons.org/share-your-work/public-domain/cc0/):

rem To the extent possible under law, SparkliTwizzl has waived all copyright and related or neighboring rights to this file. This work is published from: United States.



rem newline hack to allow single-echo line breaks
rem note: must be used as !nl!, not %nl%
setlocal EnableDelayedExpansion
(set nl=^
%=intentionallyEmpty=%
)

cd %localhost%
@echo off



rem generate license file
echo %~n0%~x0 is voluntarily released into the public domain via the Creative Commons Zero License (https://creativecommons.org/share-your-work/public-domain/cc0/):!nl!!nl!To the extent possible under law, SparkliTwizzl has waived all copyright and related or neighboring rights to %~n0%~x0. This work is published from: United States.>LICENSE



set version=0.1

set inputFile=testInput.akf
set outputFile=testOutput.ahk

echo ;generated by %~n0%~x0 v%version% on %date%!nl!>%outputFile%



set inputDataLineCount=0
for /f "tokens=*" %%x in (%inputFile%) do (
    set /a inputDataLineCount+=1
    set inputData[!inputDataLineCount!]=%%x
)



pause
