using Microsoft.VisualStudio.TestTools.UnitTesting;
using Petrichor.ShortcutScriptGeneration.Containers;
using Petrichor.Common.Info;
using Petrichor.Logging;
using Petrichor.TestShared.Info;
using Petrichor.TestShared.Utilities;


namespace Petrichor.ShortcutScriptGeneration.Utilities.Tests
{
	[ TestClass ]
	public class ShortcutScriptGeneratorTests
	{
		public struct TestData
		{
			public static ShortcutScriptEntry[] Entries => new[]
			{
				new ShortcutScriptEntry( new(){ new( "name", "tag" ) }, "pronoun", "decoration" ),
			};
			public static string[] Templates => new[]
			{
				"::@`tag`:: `name`",
				"::@$&`tag`:: `name` `pronoun` `decoration`",
			};
			public static ShortcutScriptInput Input => new( Entries!, Metadata!, Templates! );
			public static string[] Macros => new[]
			{
				"::@tag:: name",
				"::@$&tag:: name pronoun decoration",
			};
			public static ShortcutScriptMetadata Metadata => new("./IconDefault.ico");
			public static string[] GeneratedOutputFileContents => new[]
			{
				$"; Generated by { AppInfo.AppNameAndVersion } AutoHotkey shortcut script generator",
				"; https://github.com/SparkliTtwizzl/petrichor",
				"",
				"",
				"#SingleInstance Force",
				"",
				"::@tag:: name",
				"::@$&tag:: name pronoun decoration",
			};
		}


		public ShortcutScriptGenerator? ScriptGenerator;


		[TestInitialize ]
		public void Setup()
		{
			TestUtilities.InitializeLoggingForTests();
			ScriptGenerator = new ShortcutScriptGenerator();
		}


		[ TestMethod ]
		public void GenerateMacrosFromTemplatesTest_Success()
		{
			var expected = TestData.Macros;
			var actual = ScriptGenerator!.GenerateMacrosFromInput( TestData.Input ).ToArray();

			Log.Info( "expected:" );
			foreach ( var line in expected )
			{
				Log.Info( $"[{ line }]" );
			}
			Log.WriteLine();
			Log.Info( "actual:" );
			foreach ( var line in actual )
			{
				Log.Info( $"[{ line }]" );
			}

			CollectionAssert.AreEqual( expected, actual );
		}

		[ TestMethod ]
		public void GenerateScriptTest_Success()
		{
			var outputFile = $@"{ TestDirectories.TestOutputDirectory }\{ nameof( ShortcutScriptGenerator ) }_{ nameof( GenerateScriptTest_Success ) }.ahk";
			ScriptGenerator!.GenerateScript( TestData.Macros, outputFile );

			var expected = TestData.GeneratedOutputFileContents;
			var actual = File.ReadAllLines( outputFile );
			CollectionAssert.AreEqual( expected, actual );
		}
	}
}