#if RELEASE
using System.Diagnostics;
using System.IO;
#endif
using System.Reflection;

#if DEBUG
using PluralityUtilities.AutoGeneratedFiles;
#endif
using PluralityUtilities.Logging;


#if DEBUG
Log.SetLogFolder(ProjectDirectories.RunDir + "log/");
#elif RELEASE
Log.SetLogFolder(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + "/" + Process.GetCurrentProcess().ProcessName + "_log/");
#endif

Log.WriteLine("execution started");
