//AUTO-GENERATED FILE, DO NOT EDIT; ANY CHANGES WILL BE OVERWRITTEN DURING BUILD

using System.Diagnostics;
using System.Reflection;


namespace PluralityUtilities.AutoGeneratedFiles
{
    public static class ProjectDirectories
    {
        public const string BuildDir = @"_build\";
        public const string InputDir = @"_input\";
        public const string DebugLogDir = @"_run\log\";
        public const string DebugOutputDir = @"_run\output\";
        public static readonly string DebugRunDir = $@"{ExecutingDir}_run\";
        public static readonly string ExecutingDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
        public static readonly string ReleaseLogDir = $@"{ExecutingDir}\{Process.GetCurrentProcess().ProcessName}_log\";
        public static readonly string ReleaseOutputDir = ExecutingDir;

#if DEBUG
        public static readonly string LogDir = DebugLogDir;
        public static readonly string OutputDir = DebugOutputDir;
        public static readonly string RunDir = $"{ExecutingDir}{DebugRunDir}";
#elif RELEASE
        public static readonly string LogDir = ReleaseLogDir;
        public static readonly string OutputDir = ReleaseOutputDir;
        public static readonly string RunDir = ExecutingDir;
#endif
    }
}
