//AUTO-GENERATED FILE, DO NOT EDIT; ANY CHANGES WILL BE OVERWRITTEN DURING BUILD

using System.Diagnostics;
using System.Reflection;


namespace PluralityUtilities.AutoGeneratedFiles
{
    public static class ProjectDirectories
    {
        public static readonly string BuildDir = $@"{ExecutingDir}_build\";
        public static readonly string ExecutingDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
        public static readonly string InputDir = $@"{ExecutingDir}_input\";
        public static readonly string LogDir = $@"{ExecutingDir}_log\";
        public static readonly string OutputDir = $@"{ExecutingDir}_output\";
    }
}
